### ISSUE TITLE
Meetup on Jan Devshop in SF?

### ISSUE THREAD

**Issue by yubozhao** [stubailo/meteor-components#1]
Hi @stubailo 

I have been using this component package a lot recently and have few ideas based on my use cases in my fork.  I would love to meet up with you in January's devshop SF if you are around.

**Comment by stubailo** [comment]
Sounds great! I'll definitely be there. It would be great to know what issues you are running into and what could be better.

**Comment by yubozhao** [comment]
I will clean up my fork and let you have a look. 

I included the templateInstance as _templateInstance inside componentInstance, so I could have better access to the outter templates.
Also create function that  help the component instance to look up prop on the application level.  

For example

```
<template name="outer_template">
    {{#my_component}}
    {{/my_component}}
</template>
Template.outer_template.someProp = {};
Component.define(Template.my_component, {
   created: function () {
      var self = this;
      var applicationLevelProp = self.lookupProp(self._templateInstance.view, 'someProp');
   }
});
```
